using JLD2
using Test
using WaveGreen2D.Chebyshev: ChebyshevSeries, gradient, hessian, contains


# This script contais the tests for the Chebyshev series that approximate L₁ and L₂. The
# reference data is generated by the script at ../chebcoefs/chebseries_test_data.jl


cs_jld2 = jldopen("../src/chebyshev_series.jld2")

const L₁_series = read(cs_jld2, "L₁_series")
const L₂_series = read(cs_jld2, "L₂_series")

close(cs_jld2)


function get_L₁_series_index(x::SVector{3,Float64})
    u = SVector{3,Float64}(x[1], x[2], log(x[3]))

    if contains(L₁_series[1], x)
        return 1
    elseif contains(L₁_series[2], u)
        return 2
    elseif contains(L₁_series[3], u)
        return 3
    else
        throw(DomainError(x, "Point not in the domain of L₁ Chebyshev series."))
    end
end


function get_L₂_series_index(x::SVector{3,Float64})
    u = SVector{3,Float64}(x[1], x[2], log(x[3]))

    if contains(L₂_series[1], u)
        return 1
    elseif contains(L₂_series[2], u)
        return 2
    elseif contains(L₂_series[3], u)
        return 3
    elseif contains(L₂_series[4], u)
        return 4
    else
        throw(DomainError(x, "Point not in the domain of L₂ Chebyshev series."))
    end
end


function L₁(A::Float64, B₁::Float64, H::Float64)
    x = SVector{3,Float64}(A, B₁, H)
    u = SVector{3,Float64}(A, B₁, log(H))
    i = get_L₁_series_index(x)

    if i == 1
        return L₁_series[i](x)
    end

    return L₁_series[i](u)
end


function ∇L₁(A::Float64, B₁::Float64, H::Float64)
    x = SVector{3,Float64}(A, B₁, H)
    u = SVector{3,Float64}(A, B₁, log(H))
    i = get_L₁_series_index(x)

    if i == 1
        return gradient(L₁_series[i], x)
    end

    L, ∇ᵤL = gradient(L₁_series[i], u)

    # ∂L/∂x = ∂L/∂u ⋅ ∂u/∂x
    ∇L = SVector{3,Float64}(∇ᵤL[1], ∇ᵤL[2], ∇ᵤL[3] / H)

    return L, ∇L
end


function HL₁(A::Float64, B₁::Float64, H::Float64)
    x = SVector{3,Float64}(A, B₁, H)
    u = SVector{3,Float64}(A, B₁, log(H))
    i = get_L₁_series_index(x)

    if i == 1
        return hessian(L₁_series[i], x)
    end

    L, ∇ᵤL, HᵤL = hessian(L₁_series[i], u)

    # ∂L/∂x = ∂L/∂u ⋅ ∂u/∂x
    ∇L = SVector{3,Float64}(∇ᵤL[1], ∇ᵤL[2], ∇ᵤL[3] / H)

    # ∂²L/∂x² = ∂L/∂u ⋅ ∂²u/∂x² + ∂²L/∂u² ⋅ (∂u/∂x)²
    HL¹ = zero(MMatrix{3,3,Float64,9})
    HL¹[3, 3] = -∇ᵤL[3] / H^2

    HL² = MMatrix{3,3,Float64,9}(HᵤL)
    HL²[3, :] .*= 1 / H
    HL²[:, 3] .*= 1 / H

    HL = SMatrix{3,3,Float64,9}(HL¹ + HL²)

    return L, ∇L, HL
end


function L₂(A::Float64, B₂::Float64, H::Float64)
    x = SVector{3,Float64}(A, B₂, H)
    u = SVector{3,Float64}(A, B₂, log(H))
    i = get_L₂_series_index(x)
    return L₂_series[i](u)
end


function ∇L₂(A::Float64, B₂::Float64, H::Float64)
    x = SVector{3,Float64}(A, B₂, H)
    u = SVector{3,Float64}(A, B₂, log(H))
    i = get_L₂_series_index(x)
    L, ∇ᵤL = gradient(L₂_series[i], u)

    # ∂L/∂x = ∂L/∂u ⋅ ∂u/∂x
    ∇L = SVector{3,Float64}(∇ᵤL[1], ∇ᵤL[2], ∇ᵤL[3] / H)

    return L, ∇L
end


function HL₂(A::Float64, B₂::Float64, H::Float64)
    x = SVector{3,Float64}(A, B₂, H)
    u = SVector{3,Float64}(A, B₂, log(H))
    i = get_L₂_series_index(x)
    L, ∇ᵤL, HᵤL = hessian(L₂_series[i], u)

    # ∂L/∂x = ∂L/∂u ⋅ ∂u/∂x
    ∇L = SVector{3,Float64}(∇ᵤL[1], ∇ᵤL[2], ∇ᵤL[3] / H)

    # ∂²L/∂x² = ∂L/∂u ⋅ ∂²u/∂x² + ∂²L/∂u² ⋅ (∂u/∂x)²
    HL¹ = zero(MMatrix{3,3,Float64,9})
    HL¹[3, 3] = -∇ᵤL[3] / H^2

    HL² = MMatrix{3,3,Float64,9}(HᵤL)
    HL²[3, :] .*= 1 / H
    HL²[:, 3] .*= 1 / H

    HL = SMatrix{3,3,Float64,9}(HL¹ + HL²)

    return L, ∇L, HL
end


tol_L = 10^2 * eps()
tol_∇L = 10^4 * eps()
tol_HL = 10^6 * eps()


@testset "L₁ Chebyshev" begin
    @load "data/l1_test_data.jld2" x1 L1 ∇L1 HL1

    npoints = length(x1)

    C1 = Vector{Float64}(undef, npoints)
    C1g = Vector{Float64}(undef, npoints)
    C1h = Vector{Float64}(undef, npoints)

    ∇C1 = Matrix{Float64}(undef, npoints, 3)
    ∇C1h = Matrix{Float64}(undef, npoints, 3)

    HC1 = Array{Float64,3}(undef, npoints, 3, 3)

    for i in 1:npoints
        y₁ = L₁(x1[i]...)
        y₂, ∇y₂ = ∇L₁(x1[i]...)
        y₃, ∇y₃, Hy₃ = HL₁(x1[i]...)

        C1[i] = y₁
        C1g[i] = y₂
        C1h[i] = y₃
        ∇C1[i, :] .= ∇y₂
        ∇C1h[i, :] .= ∇y₃
        HC1[i, :, :] .= Hy₃
    end

    # Test if ChebyshevSeries, gradient and hessian return the same value of L₁
    @test C1 == C1g
    @test C1 == C1h

    # Test if gradient and hessian return the same value of ∇L₁
    @test ∇C1 == ∇C1h

    @test all(isapprox.(L1, C1; rtol=tol_L, atol=tol_L))
    @test all(isapprox.(∇L1, ∇C1; rtol=tol_∇L, atol=tol_∇L))
    @test all(isapprox.(HL1, HC1; rtol=tol_HL, atol=tol_HL))
end


@testset "L₂ Chebyshev" begin
    @load "data/l2_test_data.jld2" x2 L2 ∇L2 HL2

    npoints = length(x2)

    C2 = Vector{Float64}(undef, npoints)
    C2g = Vector{Float64}(undef, npoints)
    C2h = Vector{Float64}(undef, npoints)

    ∇C2 = Matrix{Float64}(undef, npoints, 3)
    ∇C2h = Matrix{Float64}(undef, npoints, 3)

    HC2 = Array{Float64,3}(undef, npoints, 3, 3)

    for i in 1:npoints
        y₁ = L₂(x2[i]...)
        y₂, ∇y₂ = ∇L₂(x2[i]...)
        y₃, ∇y₃, Hy₃ = HL₂(x2[i]...)

        C2[i] = y₁
        C2g[i] = y₂
        C2h[i] = y₃
        ∇C2[i, :] .= ∇y₂
        ∇C2h[i, :] .= ∇y₃
        HC2[i, :, :] .= Hy₃
    end

    # Test if ChebyshevSeries, gradient and hessian return the same value of L₁
    @test C2 == C2g
    @test C2 == C2h

    # Test if gradient and hessian return the same value of ∇L₁
    @test ∇C2 == ∇C2h

    @test all(isapprox.(L2, C2; rtol=tol_L, atol=tol_L))
    @test all(isapprox.(∇L2, ∇C2; rtol=tol_∇L, atol=tol_∇L))
    @test all(isapprox.(HL2, HC2; rtol=tol_HL, atol=tol_HL))
end
