using JLD2
using Test
using WaveGreen2D.NearField: L₁, ∇L₁, HL₁, L₂, ∇L₂, HL₂


# This script contais the tests for the Chebyshev series that approximate L₁ and L₂. The
# reference data is generated by the script at ../chebcoefs/chebseries_test_data.jl


tol_L = 10^2 * eps()
tol_∇L = 10^4 * eps()
tol_HL = 10^6 * eps()


@testset "L₁ Chebyshev" begin
    @load "data/l1_test_data.jld2" x1 L1 ∇L1 HL1

    npoints = length(x1)

    C1 = Vector{Float64}(undef, npoints)
    C1g = Vector{Float64}(undef, npoints)
    C1h = Vector{Float64}(undef, npoints)

    ∇C1 = Matrix{Float64}(undef, npoints, 3)
    ∇C1h = Matrix{Float64}(undef, npoints, 3)

    HC1 = Array{Float64, 3}(undef, npoints, 3, 3)

    for i in 1:npoints
        y₁ = L₁(x1[i]...)
        y₂, ∇y₂ = ∇L₁(x1[i]...)
        y₃, ∇y₃, Hy₃ = HL₁(x1[i]...)

        C1[i] = y₁
        C1g[i] = y₂
        C1h[i] = y₃
        ∇C1[i, :] .= ∇y₂
        ∇C1h[i, :] .= ∇y₃
        HC1[i, :, :] .= Hy₃
    end

    # Test if ChebyshevSeries, gradient and hessian return the same value of L₁
    @test C1 == C1g
    @test C1 == C1h

    # Test if gradient and hessian return the same value of ∇L₁
    @test ∇C1 == ∇C1h

    @test all(isapprox.(L1, C1; rtol=tol_L, atol=tol_L))
    @test all(isapprox.(∇L1, ∇C1; rtol=tol_∇L, atol=tol_∇L))
    @test all(isapprox.(HL1, HC1; rtol=tol_HL, atol=tol_HL))
end


@testset "L₂ Chebyshev" begin
    @load "data/l2_test_data.jld2" x2 L2 ∇L2 HL2

    npoints = length(x2)

    C2 = Vector{Float64}(undef, npoints)
    C2g = Vector{Float64}(undef, npoints)
    C2h = Vector{Float64}(undef, npoints)

    ∇C2 = Matrix{Float64}(undef, npoints, 3)
    ∇C2h = Matrix{Float64}(undef, npoints, 3)

    HC2 = Array{Float64, 3}(undef, npoints, 3, 3)

    for i in 1:npoints
        y₁ = L₂(x2[i]...)
        y₂, ∇y₂ = ∇L₂(x2[i]...)
        y₃, ∇y₃, Hy₃ = HL₂(x2[i]...)

        C2[i] = y₁
        C2g[i] = y₂
        C2h[i] = y₃
        ∇C2[i, :] .= ∇y₂
        ∇C2h[i, :] .= ∇y₃
        HC2[i, :, :] .= Hy₃
    end

    # Test if ChebyshevSeries, gradient and hessian return the same value of L₁
    @test C2 == C2g
    @test C2 == C2h

    # Test if gradient and hessian return the same value of ∇L₁
    @test ∇C2 == ∇C2h

    @test all(isapprox.(L2, C2; rtol=tol_L, atol=tol_L))
    @test all(isapprox.(∇L2, ∇C2; rtol=tol_∇L, atol=tol_∇L))
    @test all(isapprox.(HL2, HC2; rtol=tol_HL, atol=tol_HL))
end
